<a href="https://colab.research.google.com/github/JosueAfouda/MLflow/blob/main/first_model_with_MLflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#pip install mlflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 17.9 MB 471 kB/s 
     |████████████████████████████████| 146 kB 56.3 MB/s 
     |████████████████████████████████| 209 kB 53.6 MB/s 
     |████████████████████████████████| 596 kB 50.8 MB/s 
     |████████████████████████████████| 81 kB 5.6 MB/s 
     |████████████████████████████████| 181 kB 37.8 MB/s 
     |████████████████████████████████| 79 kB 6.6 MB/s 
     |████████████████████████████████| 54 kB 2.7 MB/s 
     |████████████████████████████████| 63 kB 1.6 MB/s 
     |████████████████████████████████| 78 kB 7.1 MB/s 
  Created wheel for databricks-cli: filename=databricks_cli-0.17.0-py3-none-any.whl size=141960 sha256=6c31a7f91ea6d8db1dd0c9859e54c968a9a99f0e9ecdd87dc7f02e364de8b677
  Stored in directory: /root/.cache/pip/wheels/55/c3/db/33705569425fd2bdc9ea73051a8053fa26965c2bce8a146747
Successfully built databricks-cli
  Attempting uninstall

In [2]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
dataset = datasets.load_iris()
seed = 123
X_train, X_test, y_train, y_test = train_test_split(
    dataset.data,
    dataset.target,
    test_size = 0.4,
    random_state = seed
)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(90, 4)
(90,)
(60, 4)
(60,)


In [12]:
X_train

array([[4.5, 2.3, 1.3, 0.3],
       [6.7, 3.3, 5.7, 2.1],
       [5.7, 3. , 4.2, 1.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.8, 3.4, 1.6, 0.2],
       [6.3, 2.9, 5.6, 1.8],
       [6.4, 2.9, 4.3, 1.3],
       [7.7, 2.8, 6.7, 2. ],
       [7.7, 2.6, 6.9, 2.3],
       [5.1, 3.8, 1.9, 0.4],
       [6.4, 3.2, 4.5, 1.5],
       [5.5, 2.4, 3.7, 1. ],
       [5.9, 3. , 5.1, 1.8],
       [4.8, 3. , 1.4, 0.1],
       [7.2, 3. , 5.8, 1.6],
       [6.3, 3.3, 4.7, 1.6],
       [7. , 3.2, 4.7, 1.4],
       [5. , 3. , 1.6, 0.2],
       [6.4, 2.8, 5.6, 2.1],
       [6.3, 2.5, 5. , 1.9],
       [5. , 3.5, 1.6, 0.6],
       [4.9, 3. , 1.4, 0.2],
       [6.1, 2.8, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 4. , 1.2, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [5.5, 2.4, 3.8, 1.1],
       [5. , 3.4, 1.6, 0.4],
       [5.9, 3.2, 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [4.8, 3.1, 1.6, 0.2],
       [6.7, 2.5, 5.8, 1.8],
       [5.7, 4.4, 1.5, 0.4],
       [5.7, 3

In [25]:
y_train

array([0, 2, 1, 0, 0, 2, 1, 2, 2, 0, 1, 1, 2, 0, 2, 1, 1, 0, 2, 2, 0, 0,
       1, 1, 2, 0, 0, 1, 0, 1, 2, 0, 2, 0, 0, 1, 0, 0, 1, 2, 1, 1, 1, 0,
       0, 1, 2, 0, 0, 1, 1, 1, 2, 1, 1, 1, 2, 0, 0, 1, 2, 2, 2, 2, 0, 1,
       0, 1, 1, 0, 1, 2, 1, 2, 2, 0, 1, 0, 2, 2, 1, 1, 2, 2, 1, 0, 1, 1,
       2, 2])

In [3]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

En ajoutant quelques lignes de code au script précédent, on peut déjà enregistrer une première expérience avec MLflow.

In [4]:
from sklearn.linear_model import LogisticRegression
import mlflow
# Définition d'une expérience (Une expérience peut contenir plusieurs *runs*)
mlflow.set_experiment("Reg_Logistic_Models")
mlflow.sklearn.autolog() # Ici on fait appel à l'API MLflow qui intégre les algos de Scikit-Learn.
                        # C'est grâce à ce code qu'on enregistre toutes les métriques et métadonnées de cette expérience (Module MLflow Tracking)
with mlflow.start_run(run_name = 'reg_logistic_defaut'):
  clf = LogisticRegression()
  clf.fit(X_train, y_train)

2022/08/05 15:37:45 INFO mlflow.tracking.fluent: Experiment with name 'Reg_Logistic_Models' does not exist. Creating a new experiment.
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [5]:
# Création d'un second run dans la même expérience
with mlflow.start_run(run_name = 'reg_logistic_max_iter_200'):
  clf2 = LogisticRegression(max_iter=200)
  clf2.fit(X_train, y_train)

In [26]:
# Création d'une seconde expérience
mlflow.set_experiment("Decision_Tree_Models")
mlflow.sklearn.autolog()
from sklearn.tree import DecisionTreeClassifier
with mlflow.start_run(run_name = 'decision_tree_defaut'):
  dt1 = DecisionTreeClassifier(random_state=seed)
  dt1.fit(X_train, y_train)

2022/08/05 16:00:04 INFO mlflow.tracking.fluent: Experiment with name 'Decision_Tree_Models' does not exist. Creating a new experiment.


In [27]:
with mlflow.start_run(run_name = 'decision_tree_max_depth3'):
  dt2 = DecisionTreeClassifier(random_state=seed, max_depth=3)
  dt2.fit(X_train, y_train)

In [22]:
import numpy as np
new_data = np.array([[6.5, 3.2, 5.5, 1.9]])
new_data

array([[6.5, 3.2, 5.5, 1.9]])

In [23]:
new_data.shape

(1, 4)

In [24]:
# Prédictions
logged_model = 'runs:/12366ea03957424891b6f90e65086664/model'

# Load model as a PyFuncModel.
loaded_model = mlflow.pyfunc.load_model(logged_model)

# Predict on a Pandas DataFrame.
import pandas as pd
prediction = loaded_model.predict(new_data)
prediction

array([2])

In [9]:
#pip install pyngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 745 kB 7.7 MB/s 
  Created wheel for pyngrok: filename=pyngrok-5.1.0-py3-none-any.whl size=19007 sha256=b95ed2f31c52a6a3268ddb2fc515c356dd4f39da6423a121e44ed4f8718d93e0
  Stored in directory: /root/.cache/pip/wheels/bf/e6/af/ccf6598ecefecd44104069371795cb9b3afbcd16987f6ccfb3
Successfully built pyngrok


In [29]:
from pyngrok import ngrok
# Terminate open tunnels if exist
ngrok.kill()

# Setting the authtoken (optional)
# Get your authtoken from https://dashboard.ngrok.com/auth
NGROK_AUTH_TOKEN = "" 
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# Open an HTTPs tunnel on port 5000 for http://localhost:5000
ngrok_tunnel = ngrok.connect(addr="5000", proto="http", bind_tls=True)
print("MLflow Tracking UI:", ngrok_tunnel.public_url)

MLflow Tracking UI: https://1d60-34-82-250-245.ngrok.io


In [30]:
!mlflow ui

[2022-08-05 16:02:30 +0000] [699] [INFO] Starting gunicorn 20.1.0
[2022-08-05 16:02:30 +0000] [699] [INFO] Listening at: http://127.0.0.1:5000 (699)
[2022-08-05 16:02:30 +0000] [699] [INFO] Using worker: sync
[2022-08-05 16:02:30 +0000] [702] [INFO] Booting worker with pid: 702
[2022-08-05 16:31:48 +0000] [699] [INFO] Handling signal: int
[2022-08-05 16:31:48 +0000] [702] [INFO] Worker exiting (pid: 702)

Aborted!
[2022-08-05 16:31:49 +0000] [699] [INFO] Shutting down: Master
